language: node_js
node_js:
  - "7"

branches:
  only:
    - master
    - develop

before_script:
  - npm install -g firebase-tools
  - npm install -g @angular/cli

script:
  - ng build --prod --output-hashing=bundles
