language: node_js
node_js:
  - "8"

branches:
  only:
    - master
    - develop
    - travis-fix

before_script:
  - npm install -g firebase-tools

script:
  - ng build --prod --output-hashing=bundles
