sudo: required
dist: trusty
language: node_js
node_js:
  - "8"

branches:
  only:
    - master
    - develop
    - travis-fix

before_script:
  - npm install -g firebase-tools

install:
  - npm install
  - npm install @angular/material@2.0.0-beta.10
cache:
  directories:
    - "node_modules"

script:
  - ng build --prod --output-hashing=bundles --no-aot
